# Generated by Django 4.2 on 2025-05-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_contactmessage_alter_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Vendor', 'Nhà cung cấp'), ('Customer', 'Khách hàng')], default=None, max_length=255, null=True),
        ),
    ]
