# Generated by Django 4.2 on 2025-05-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_service_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Chờ xác nhận'), ('Processing', 'Đang xử lý'), ('Shipped', 'Đang giao hàng'), ('Fulfilled', 'Hoàn thành'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('COD', 'Thanh toán khi nhận hàng'), ('ZaloPay', 'ZaloPay'), ('Momo', 'Ví MoMo'), ('BankTransfer', 'Chuyển khoản ngân hàng')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Đã thanh toán'), ('Processing', 'Đang xử lý'), ('Failed', 'Thất bại')], default='Processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Chờ xác nhận'), ('Processing', 'Đang xử lý'), ('Shipped', 'Đang giao hàng'), ('Fulfilled', 'Hoàn thành'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shipping_service',
            field=models.CharField(blank=True, choices=[('GiaoHangNhanh', 'Giao Hàng Nhanh'), ('ViettelPost', 'Viettel Post'), ('GHTK', 'Giao Hàng Tiết Kiệm')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Published', 'Đã đăng'), ('Draft', 'Bản nháp'), ('Disabled', 'Đã tắt')], default='Published', max_length=50),
        ),
    ]
