# Generated by Django 4.2 on 2025-05-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_address_address_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('New Order', 'Đơn hàng mới'), ('Item Shipped', 'Đơn hàng đã gửi đi'), ('Item Delivered', 'Đơn hàng đã giao')], default=None, max_length=100),
        ),
    ]
