# Generated by Django 4.2 on 2025-05-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_notifications_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='province',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
    ]
