# Generated by Django 4.2 on 2025-05-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Bản nháp'), ('Published', 'Đã đăng')], default='Published', max_length=10),
        ),
    ]
